# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

grp_CD_XZ <- function(y, X, Z, group, pBigMat, J_q, dims, beta, offset, family, link, init, XZ_group, K, penalty, params) {
    .Call('_glmmPen_grp_CD_XZ', PACKAGE = 'glmmPen', y, X, Z, group, pBigMat, J_q, dims, beta, offset, family, link, init, XZ_group, K, penalty, params)
}

soft_thresh <- function(zeta, lambda) {
    .Call('_glmmPen_soft_thresh', PACKAGE = 'glmmPen', zeta, lambda)
}

MCP_soln <- function(zeta, nu, lambda, gamma, alpha) {
    .Call('_glmmPen_MCP_soln', PACKAGE = 'glmmPen', zeta, nu, lambda, gamma, alpha)
}

SCAD_soln <- function(zeta, nu, lambda, gamma, alpha) {
    .Call('_glmmPen_SCAD_soln', PACKAGE = 'glmmPen', zeta, nu, lambda, gamma, alpha)
}

sample_mc_inner_gibbs <- function(f, z, y, t, NMC, u0, trace) {
    .Call('_glmmPen_sample_mc_inner_gibbs', PACKAGE = 'glmmPen', f, z, y, t, NMC, u0, trace)
}

sample_mc_inner_gibbs2 <- function(f, z, y, t, NMC, u0, proposal_SD, batch, batch_length, offset, burnin_batchnum, trace) {
    .Call('_glmmPen_sample_mc_inner_gibbs2', PACKAGE = 'glmmPen', f, z, y, t, NMC, u0, proposal_SD, batch, batch_length, offset, burnin_batchnum, trace)
}

#' @export
sample_mc_gibbs_adapt_rw <- function(f, z, y, NMC, u0, proposal_SD, batch, batch_length, offset, burnin_batchnum, trace) {
    .Call('_glmmPen_sample_mc_gibbs_adapt_rw', PACKAGE = 'glmmPen', f, z, y, NMC, u0, proposal_SD, batch, batch_length, offset, burnin_batchnum, trace)
}

arma_test_value <- function(x) {
    invisible(.Call('_glmmPen_arma_test_value', PACKAGE = 'glmmPen', x))
}

arma_test_ref <- function(x) {
    invisible(.Call('_glmmPen_arma_test_ref', PACKAGE = 'glmmPen', x))
}

arma_test_const_ref <- function(x) {
    invisible(.Call('_glmmPen_arma_test_const_ref', PACKAGE = 'glmmPen', x))
}

#' @export
Znew_gen2 <- function(U, Z, g, cols, n, q, d, pBigMat, J) {
    invisible(.Call('_glmmPen_Znew_gen2', PACKAGE = 'glmmPen', U, Z, g, cols, n, q, d, pBigMat, J))
}

orthog_inner <- function(X, g, gmax, gmin, n) {
    .Call('_glmmPen_orthog_inner', PACKAGE = 'glmmPen', X, g, gmax, gmin, n)
}

invlink <- function(link, eta) {
    .Call('_glmmPen_invlink', PACKAGE = 'glmmPen', link, eta)
}

Qfun <- function(y, X, Z, pBigMat, group, J_q, beta, offset, dims, family, link) {
    .Call('_glmmPen_Qfun', PACKAGE = 'glmmPen', y, X, Z, pBigMat, group, J_q, beta, offset, dims, family, link)
}

