# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLik_cpp <- function(U_means, sigma, M, group, n_levels, df, y, eta_fef, Z, Gamma, family) {
    .Call('_glmmPen_logLik_cpp', PACKAGE = 'glmmPen', U_means, sigma, M, group, n_levels, df, y, eta_fef, Z, Gamma, family)
}

logLik_modif <- function(U_means, sigma, M, group, n_levels, df, y, eta_fef, Z, Gamma, family) {
    .Call('_glmmPen_logLik_modif', PACKAGE = 'glmmPen', U_means, sigma, M, group, n_levels, df, y, eta_fef, Z, Gamma, family)
}

logLik_MCI <- function(M, group, n_levels, y, eta_fef, Z, Gamma, family) {
    .Call('_glmmPen_logLik_MCI', PACKAGE = 'glmmPen', M, group, n_levels, y, eta_fef, Z, Gamma, family)
}

#' Obtaining Rejection Sampling Monte Carlo Draws
#' 
#' Description
#' 
#' @param f a one-column matrix of the fixed effects component of the linear predictor for 
#' the individuals/observations in a specific group (i.e. group k)
#' @param z a sub-matrix of the full Z matrix (see output information of \code{\link{formulaData}} 
#' for details); the columns pertain to the columns of Z associated 
#' with a particular group, the rows peratin to the rows of Z that are associated with
#' the group of interest
#' @param y the sub-vector of the original response vector that is associated with the particular
#' group of interest
#' @param NMC positive integer, number of Monte Carlo draws to obtain
#' @param trace an integer specifying print output to include as function runs. If trace = 2, then 
#' will output acceptance rate information
#' 
#' @return A matrix of Rejection sampling Monte Carlo draws. nrows: \code{NMC}, columns: 
#' each column pertains to one of the q random effects variables that are associated with the 
#' group of interest (ncols = q). If the algorithm errored-out due to an unacceptably low 
#' acceptance rate, then a matrix of all zeros of dimension (NMC-3)xq is output.
#' 
#' @export
sample_mc_inner <- function(f, z, y, t, NMC, trace) {
    .Call('_glmmPen_sample_mc_inner', PACKAGE = 'glmmPen', f, z, y, t, NMC, trace)
}

sample_mc_inner_gibbs <- function(f, z, y, t, NMC, u0, trace) {
    .Call('_glmmPen_sample_mc_inner_gibbs', PACKAGE = 'glmmPen', f, z, y, t, NMC, u0, trace)
}

sample_mc_inner_gibbs2 <- function(f, z, y, t, NMC, u0, proposal_SD, batch, trace) {
    .Call('_glmmPen_sample_mc_inner_gibbs2', PACKAGE = 'glmmPen', f, z, y, t, NMC, u0, proposal_SD, batch, trace)
}

#' @export
sample_mc_gibbs_rw <- function(f, z, y, t, NMC, u0, proposal_SD, batch, batch_length, offset, trace) {
    .Call('_glmmPen_sample_mc_gibbs_rw', PACKAGE = 'glmmPen', f, z, y, t, NMC, u0, proposal_SD, batch, batch_length, offset, trace)
}

arma_test_value <- function(x) {
    invisible(.Call('_glmmPen_arma_test_value', PACKAGE = 'glmmPen', x))
}

arma_test_ref <- function(x) {
    invisible(.Call('_glmmPen_arma_test_ref', PACKAGE = 'glmmPen', x))
}

arma_test_const_ref <- function(x) {
    invisible(.Call('_glmmPen_arma_test_const_ref', PACKAGE = 'glmmPen', x))
}

#' @export
Znew_gen2 <- function(U, Z, g, cols, n, q, d, pBigMat, J) {
    invisible(.Call('_glmmPen_Znew_gen2', PACKAGE = 'glmmPen', U, Z, g, cols, n, q, d, pBigMat, J))
}

orthog_inner <- function(X, g, gmax, gmin, n) {
    .Call('_glmmPen_orthog_inner', PACKAGE = 'glmmPen', X, g, gmax, gmin, n)
}

