# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_mc_inner <- function(f, z, y, t, NMC) {
    .Call('_glmmPen_sample_mc_inner', PACKAGE = 'glmmPen', f, z, y, t, NMC)
}

sample_mc_inner_gibbs <- function(f, z, y, t, NMC, u0) {
    .Call('_glmmPen_sample_mc_inner_gibbs', PACKAGE = 'glmmPen', f, z, y, t, NMC, u0)
}

arma_test_value <- function(x) {
    invisible(.Call('_glmmPen_arma_test_value', PACKAGE = 'glmmPen', x))
}

arma_test_ref <- function(x) {
    invisible(.Call('_glmmPen_arma_test_ref', PACKAGE = 'glmmPen', x))
}

arma_test_const_ref <- function(x) {
    invisible(.Call('_glmmPen_arma_test_const_ref', PACKAGE = 'glmmPen', x))
}

Znew_gen2 <- function(U, Z, g, cols, n, q, d, pBigMat, J) {
    invisible(.Call('_glmmPen_Znew_gen2', PACKAGE = 'glmmPen', U, Z, g, cols, n, q, d, pBigMat, J))
}

orthog_inner <- function(X, g, gmax, gmin, n) {
    .Call('_glmmPen_orthog_inner', PACKAGE = 'glmmPen', X, g, gmax, gmin, n)
}

